# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b656c190ae7d71d4c0e6e5a5eb6eb4d329053533be89de5062017df902362c0aecb3070399ad0e4ea03a4c891eb8da9c8170dc538ccdf2e66270a6ac962e5f09

test:
  secret_key_base: d9f308ff831e66937f70803ff084e0795ea45725279bc1f76776a1a68133bd56b2a894ab6ec70a23930eb704f527ab4fb9b9a524a52c88000752fd83191ac0be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
